import React from "react";
import { Link } from "react-router-dom";

function TermsPage() {
  return (
    <div className="bg-info min-vh-100 py-5">
      <div className="container py-4">
        <div className="row justify-content-center">
          <div className="col-lg-10">
            <div className="card shadow-sm border-0 rounded-4 p-5">
              
              <div className="text-center mb-2">
                <h1 className="fw-bold display-5">Terms and Conditions</h1>
              </div>

              <div className="terms-content text-secondary" style={{ lineHeight: "1.8" }}>
                
                <h4 className="fw-bold text-dark mt-4 mb-3">Acceptance of Terms</h4>
                <p>
                  By accessing and using AgePredict.ai (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this Service.
                </p>

                <h4 className="fw-bold text-dark mt-4 mb-3">Description of Service</h4>
                <p>
                  AgePredict.ai provides an artificial intelligence-based tool designed to estimate the apparent age of individuals in uploaded photographs or live webcam captures. This tool is provided for informational and entertainment purposes only.
                </p>

                <h4 className="fw-bold text-dark mt-4 mb-3">Privacy & Data Handling</h4>
                <p>
                  We prioritize your privacy. Any image uploaded or captured via webcam is processed securely in memory solely for the purpose of age estimation. <strong>We do not save, store, or transmit your images to any database</strong>, nor do we use your images to train future AI models. Once the estimation is complete, the image data is permanently discarded.
                </p>

                <h4 className="fw-bold text-dark mt-4 mb-3">Accuracy & Disclaimer</h4>
                <p>
                  The age estimations provided by AgePredict.ai are generated by a neural network and represent the <em>apparent</em> age of the subject based on facial features, lighting, and angles. 
                  <strong> The Service does not determine biological age.</strong> You acknowledge that the AI may produce inaccurate results and that the Service should not be used for legal age verification, medical, or official regulatory purposes.
                </p>

                <h4 className="fw-bold text-dark mt-4 mb-3">Limitation of Liability</h4>
                <p>
                  In no event shall AgePredict.ai, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
                </p>

                <hr className="my-5" />
                
                <div className="text-center">
                  <p className="mb-0">Questions about our Terms?</p>
                  <Link to="/contact" className="text-primary text-decoration-none fw-bold">Contact our Support Team</Link>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default TermsPage;